"""add extension.author

Revision ID: 4f2a07b8c4c1
Revises: 6b3c595a7a1e
Create Date: 2020-01-25 03:07:17.469549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2a07b8c4c1'
down_revision = '6b3c595a7a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extensions', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extensions', 'author')
    # ### end Alembic commands ###
